name: Deploy to Namecheap cPanel

on:
  push:
    branches:
      - main  # Or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/my.test.app

      - name: Restart App via SSH
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          source ~/.bash_profile
          cd ~/myapp
          npm install --production
          pkill -f "node index.js" || true
          nohup node index.js > out.log 2>&1 &
          EOF
